---
name: helm-chart

on:
  pull_request:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Create helm chart package
        run: helm package helm/

      - name: Push helm chart package
        run: helm push *.tgz oci://ghcr.io/uvaitsei