apiVersion: v2
name: openldap-helm-chart
home: https://www.openldap.org
version: 1.1.7-1
appVersion: 2.6.8
description: The OpenLDAP directory server, with support from Symas Corp.
icon: https://raw.githubusercontent.com/symas/helm-openldap/master/logo.png
keywords:
  - ldap
  - openldap
  - iam-stack
  - high availability
sources:
  - https://github.com/symas/helm-openldap
maintainers:
  - name: Symas Corp.
    email: support@symas.com
dependencies:
  - name: ltb-passwd
    version: 0.1.x
    condition: ltb-passwd.enabled
  - name: phpldapadmin
    version: 0.1.x
    condition: phpldapadmin.enabled
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: ~2
engine: gotpl
