#
# A ConfigMap spec for openldap slapd that map directly to env variables in the Pod.
# List of environment variables supported is from the docker image:
# https://hub.docker.com/r/symas/openldap/
# Note that passwords are defined as secrets
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}-env
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  LDAP_ROOT: {{ include "global.baseDomain" . }}
  LDAP_EXTRA_SCHEMAS: {{ print "cosine,inetorgperson,nis," (include "openldap.schemaFiles" .) }}
  LDAP_CUSTOM_SCHEMA_DIR: /custom-schemas
  LDAP_CUSTOM_LDIF_DIR: /custom-ldifs
  LDAP_ENTRYPOINT_INITDB_D_DIR: /custom-config
  {{- if .Values.users }}
  LDAP_USERS: {{ .Values.users }}
  {{- end }}
  {{- if .Values.userPasswords }}
  LDAP_PASSWORDS: {{ .Values.userPasswords }}
  {{- end }}
  {{- if .Values.group }}
  LDAP_GROUP: {{ .Values.group }}
  {{- end }}
  {{- if .Values.initTLSSecret.tls_enabled}}
  LDAP_ENABLE_TLS: "yes"
  LDAP_TLS_CERT_FILE: /certs/tls.crt
  LDAP_TLS_KEY_FILE: /certs/tls.key
  LDAP_TLS_CA_FILE: /certs/ca.crt
  {{- else }}
  LDAP_ENABLE_TLS: "no"
  {{- end }}
  {{- if .Values.global.configUserEnabled }}
  LDAP_CONFIG_ADMIN_ENABLED: "yes"
  LDAP_CONFIG_ADMIN_USERNAME: "{{ .Values.global.configUser }}"
  {{- else }}
  LDAP_CONFIG_ADMIN_ENABLED: "no"
  {{- end }}
  {{- if .Values.replication.enabled }}
  LDAP_SYNCPROV_ENABLE: "yes"
  {{- end }}
  LDAP_TLS_VERIFY_CLIENT: "try"
{{ toYaml .Values.env | indent 2 }}
